project_id = "mtcwareqdrkhpargfphu"

[functions.google-places-fallback]
verify_jwt = false

[functions.fedex-auth]
verify_jwt = true

[functions.fedex-shipment]
verify_jwt = true

[functions.fedex-shipment-partner]
verify_jwt = true
